#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

start() {
    mkdir -p /var/log/raspimon
    chmod 666 /var/log/raspimon
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
        echo "Installed."
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
