#!/bin/bash
### BEGIN INIT INFO
# Provides:          raspimon
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Raspimon service to ensure that certain resources are present at boot
### END INIT INFO

start() {
    mkdir -p /var/log/raspimon
    chmod 666 /var/log/raspimon
}

stop() {
    # code to stop app comes here 
    # example: killproc program_name
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
        echo "Installed."
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
